{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gearify-service.serviceAccountName" . }}
  labels:
    {{- include "gearify-service.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.serviceAccount.irsaRoleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.irsaRoleArn }}
  {{- end }}
{{- end }}
